extensions:
  health_check:
receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14268"
processors:
  batch:
    timeout: 1s
exporters:
  otlp:
    endpoint: staging.otlp.nr-data.net:4317
    headers:
      api-key: ${NEW_RELIC_INSERT_KEY}
service:
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch]
      exporters: [otlp]
  extensions: [health_check]