agentName: Python
  agentType: APM
  title: 'Python agent installation options
  metaDescription: "Here are several ways to install the Python APM agent"
  introFilePath: 'src/install/python/intro.mdx'
  agentConfigFilePath: 'src/install/config/agent-config/newrelic.ini'
  appInfo:
    - optionType: instrumentation
      label: 'What kind of instrumentation are you looking for??'
      placeholder: 'What is this placeholder thingy?'
      options:
        - value: 'manual'
          displayName: 'manual'
          logo: 'docker'
        - value: 'auto'
          displayName: 'auto'
          logo: 'glassfish'

  steps:
    - filePath: 'src/install/python/appInfo.mdx'
    - filePath: 'src/install/python/step-one.mdx'
    - filePath: 'src/install/python/step-two.mdx'
        - filePath: 'src/install/python/default.mdx'
      overrides:
        - filePath: 'src/install/auto-instrumentation/auto.mdx'
          selectedOptions:
            - optionType: auto
              options:
                - value: 'auto'
        - filePath: 'src/install/manual-instrumentation/manual.mdx'
          selectedOptions:
            - optionType: manual
              options:
                - value: 'manual'
    - filePath: 'src/install/python/step-three.mdx'
  whatsNextFilePath: 'src/install/python/whatsNext.mdx'