extends: metric
message: "Try to keep the Flesch-Kincaid grade level (%s) above 45."
link: https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests
level: error

formula: |
  (206.385-1.015 * (words / sentences)) - 84.6 * (syllables / words)
condition: "< 80"