agentName: dependabot
agentType: VM
title: 'Send dependabot data'
introFilePath: 'src/install/vm/intro.mdx'
appInfo:
  - optionType: form
    label: 'Do you want to send new or previously detected vulnerabilities?'
    placeholder: 'I want to send...'
    options:
      - value: 'new'
        displayName: 'new vulnerabilities'
      - value: 'previous'
        displayName: 'previously detected vulnerabilities'

steps:
  - filePath: 'src/install/vm/default.mdx'
    overrides:
      - filePath: 'src/install/vm/new.mdx'
        selectedOptions:
          - optionType: form
            options:
              - value: 'new'
      - filePath: 'src/install/vm/previous.mdx'
        selectedOptions:
          - optionType: form
            options:
              - value: 'previous'
  - filePath: 'src/install/monitor.mdx'
whatsNextFilePath: 'src/install/java/whatsNext.mdx'
