agentName: dotnet
agentType: APM
title: 'Monitor your .NET app'
metaDescription: "The New Relic .NET agent monitors your .NET app's performance. It works with all .NET compatible languages, such as VB.NET, C#, and CLI."
introFilePath: 'src/install/dotnet/intro.mdx'
agentConfigFilePath: 'src/install/config/agent-config/dotnet-newrelic.xml'
redirects:
appInfo:
  - optionType: docker
    label: 'Is your app in a Docker container?'
    placeholder: 'Placeholder...'
    options:
      - value: 'noDocker'
        displayName: 'No'
        logo: ''
      - value: 'yesDocker'
        displayName: 'Yes'
        logo: ''
  - optionType: deployment
    label: 'Choose your deployment'
    placeholder: 
    options:
      - value: 'linux'
        displayName: 'Linux'
        logo: ''
        recommendedGuided: true
      - value: 'windowsIis'
        displayName: 'Windows using IIS web server'
        logo: ''
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows (not using IIS)'
        logo: ''
steps:
  - filePath: 'src/install/dotnet/appInfo.mdx'
  - filePath: 'src/install/dotnet/Installation/linuxInstall.mdx'
    selectedOptions:
      - optionType: deployment
        options:
          - value: 'linux'
  - filePath: 'src/install/dotnet/Installation/windowsInstall.mdx'
    selectedOptions:
      - optionType: deployment
        options:
          - value: 'windowsInstall'
whatsNextFilePath: 'src/install/java/whatsNext.mdx'
