agentName: dotnet
agentType: APM
title: 'Monitor your .NET app'
metaDescription: "The New Relic .NET agent monitors your .NET app's performance. It works with all .NET compatible languages, such as VB.NET, C#, and CLI."
introFilePath: 'src/install/dotnet/intro.mdx'
agentConfigFilePath: 'src/install/config/agent-config/dotnet-newrelic.xml'
appInfo:
  - optionType: docker
    label: 'Docker?'
    placeholder: 'Is your app in a Docker container'
    options:
      - value: 'noDocker'
        displayName: 'No'
      - value: 'yesDocker'
        displayName: 'Yes'
  - optionType: deployment 
    label: 'install'
    placeholder: 'How do you want to install the .NET agent'
    options:
      - value: 'linux'
        displayName: 'Linux'
        recommendedGuided: true
      - value: 'windowsInstall'
        displayName: 'Windows using IIS web server'
        recommendedGuided: true
      - value: 'windowsInstallNonIis'
        displayName: 'Windows, not using IIS'
      - value: 'azureWebApps'
        displayName: 'Azure Web Apps'        
      - value: 'awsLambda'
        displayName: 'AWS Lambda'
      - value: 'nuget'
        displayName: 'via Nuget'        
steps:
  - filePath: 'src/install/dotnet/appInfo.mdx'       
  - filePath: 'src/install/dotnet/installation/default-blank.mdx' 
    overrides:
      - filePath: 'src/install/dotnet/installation/linuxInstall1.mdx'
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'linux'
      - filePath: 'src/install/dotnet/installation/windowsInstall.mdx'
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windowsInstall' 
      - filePath: 'src/install/dotnet/installation/windowsInstallNonIis.mdx'
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windowsInstallNonIis'   
  - filePath: 'src/install/dotnet/installation/default-blank.mdx' 
    overrides: 
      - filePath: 'src/install/dotnet/installation/linuxInstall2.mdx'
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'linux'
  - filePath: 'src/install/dotnet/installation/default-blank.mdx' 
    overrides: 
      - filePath: 'src/install/dotnet/installation/linuxInstall3-enable-agent.mdx'
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'linux'                  
  - filePath: 'src/install/dotnet/installation/default-blank.mdx' 
    overrides:
      - filePath: 'src/install/dotnet/installation/docker.mdx'
        selectedOptions:
          - optionType: docker
            options:
              - value: 'yesDocker'     
whatsNextFilePath: 'src/install/dotnet/whatsNext.mdx'
