agentName: dotnet
agentType: APM
title: 'Monitor your .NET app'
metaDescription: "How to install the New Relic .NET language APM agent."
introFilePath: 'src/install/dotnet/intro.mdx'
agentConfigFilePath: 'src/install/config/agent-config/dotnet-newrelic.xml'
appInfo:
  - optionType: deployment 
    label: 'Install options'
    placeholder: "Pick the option that best matches how you'll install the agent."
    options:
      - value: 'linux'
        displayName: 'Linux'
        recommendedGuided: true
      - value: 'windowsInstall'
        displayName: 'Windows, using IIS web server'
        recommendedGuided: true
      - value: 'windowsInstallNonIis'
        displayName: 'Windows, not using IIS'
      - value: 'azureWebApps'
        displayName: 'Azure Web Apps'        
      - value: 'awsLambda'
        displayName: 'AWS Lambda'
      - value: 'nuget'
        displayName: 'Nuget package'        
  - optionType: docker
    label: 'Docker?'
    placeholder: 'Is your app in a Docker container?'
    options:
      - value: 'noDocker'
        displayName: 'No'
      - value: 'yesDocker'
        displayName: 'Yes'
steps:
  - filePath: 'src/install/dotnet/appInfo-1.mdx'
  - filePath: 'src/install/dotnet/appInfo-2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'Linux'
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windowsInstall'
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windowsInstallNonIis'
  - filePath: 'src/install/dotnet/installation/windowsInstall.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windowsInstall'
          - optionType: docker
            options:
              - value: 'noDocker'
  - filePath: 'src/install/dotnet/installation/windowsInstallNonIis.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windowsInstallNonIis'
          - optionType: docker
            options:
              - value: 'noDocker'
  - filePath: 'src/install/dotnet/installation/linuxInstall1.mdx' 
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'linux'
          - optionType: docker
            options:
              - value: 'noDocker'
  - filePath: 'src/install/dotnet/installation/linuxInstall2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'linux'
          - optionType: docker
            options:
              - value: 'noDocker'
  - filePath: 'src/install/dotnet/installation/linuxInstall3-enable-agent.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'linux'
          - optionType: docker
            options:
              - value: 'noDocker'
  - filePath: 'src/install/dotnet/installation/docker.mdx'
    overrides: 
      - skip: true
        selectedOptions:
          - optionType: docker
            options:
              - value: 'noDocker' 
      - skip: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'lambda'             
      - skip: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'nuget' 
      - skip: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'azureWebApps' 
whatsNextFilePath: 'src/install/dotnet/whatsNext.mdx'
