agentName: dotnet
agentType: APM
title: 'Monitor your .NET app'
metaDescription: 'The New Relic .NET agent monitors your .NET app's performance. It works with all .NET compatible languages, such as VB.NET, C#, and CLI.'
introFilePath: 'src/install/dotnet/intro.mdx'
agentConfigFilePath: 'src/install/config/agent-config/dotnet-newrelic.xml'
redirects:
appInfo:
  - optionType: docker
    label: 'Is your app in a Docker container?'
    placeholder: 
    options:
      - value: 'noDocker'
        displayName: 'No'
        logo: ''
      - value: 'yesDocker'
        displayName: 'Yes'
        logo: ''
  - optionType: deployment
    label: 'Choose your deployment'
    placeholder: 
    options:
      - value: 'linux'
        displayName: 'Linux'
        logo: ''
      - value: 'windows'
        displayName: 'Windows (not using IIS)'
        logo: ''
      - value: 'windowsIis'
        displayName: 'Windows using IIS web server'
        logo: ''
steps:
  - filePath: 'src/install/java/appInfo.mdx'
  - filePath: 'src/install/java/download/default.mdx'
    overrides:
      - filePath: 'src/install/java/download/maven.mdx'
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'maven'
      - filePath: 'src/install/java/download/gradle.mdx'
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'gradle'
      - filePath: 'src/install/java/download/aws.mdx'
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'aws'    
  - filePath: 'src/install/java/agentConfig.mdx'
    overrides:
        - skip: true
          selectedOptions:
            - optionType: deployment
              options:
                - value: 'aws'
  - filePath: 'src/install/java/createDirectory.mdx'
    overrides:
        - filePath: 'src/install/java/download/docker-config.mdx'
          selectedOptions:
          - optionType: deployment
            options:
              - value: 'docker'
        - skip: true
          selectedOptions:
            - optionType: deployment
              options:
                - value: 'aws'
                - value: 'docker'
  - filePath: 'src/install/java/moveDirectory.mdx'
    overrides:
        - filePath: 'src/install/java/download/docker-basic.mdx'
          selectedOptions:
          - optionType: deployment
            options:
              - value: 'docker'
        - skip: true
          selectedOptions:
            - optionType: deployment
              options:
                - value: 'aws'
  - filePath: 'src/install/java/frameworkInstallation/default.mdx'
    overrides:
      - filePath: 'src/install/java/frameworkInstallation/jetty.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'jetty'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - skip: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'aws'
      - filePath: 'src/install/java/frameworkInstallation/springboot.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'springboot'
          - optionType: deployment
            options:
              - value: 'appServer'
      - filePath: 'src/install/java/frameworkInstallation/tomcat.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'tomcat'
          - optionType: deployment
            options:
              - value: 'appServer'
      - filePath: 'src/install/java/frameworkInstallation/tomcat.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'tomcat'
          - optionType: deployment
            options:
              - value: 'docker'
      - filePath: 'src/install/java/frameworkInstallation/wildfly.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'wildfly'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - filePath: 'src/install/java/frameworkInstallation/coldfusion.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'coldfusion'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - filePath: 'src/install/java/frameworkInstallation/geronimo.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'geronimo'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - filePath: 'src/install/java/frameworkInstallation/glassfish.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'glassfish'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - filePath: 'src/install/java/frameworkInstallation/grails.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'grails'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - filePath: 'src/install/java/frameworkInstallation/jboss.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'jboss'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - filePath: 'src/install/java/frameworkInstallation/play.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'play'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - filePath: 'src/install/java/frameworkInstallation/resin.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'resin'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - filePath: 'src/install/java/frameworkInstallation/solr.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'solr'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - filePath: 'src/install/java/frameworkInstallation/tanuki.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'tanuki'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - filePath: 'src/install/java/frameworkInstallation/weblogic.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'weblogic'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - filePath: 'src/install/java/frameworkInstallation/websphere.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'websphere'
          - optionType: deployment
            options:
              - value: 'appServer'
              - value: 'maven'
              - value: 'gradle'
      - skip: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'aws'
  - filePath: 'src/install/java/outro.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'aws'
whatsNextFilePath: 'src/install/java/whatsNext.mdx'
