agentName: dotnet
agentType: APM
title: 'Monitor your .NET app'
metaDescription: "The New Relic .NET agent monitors your .NET app's performance. It works with all .NET compatible languages, such as VB.NET, C#, and CLI."
introFilePath: 'src/install/dotnet/intro.mdx'
agentConfigFilePath: 'src/install/config/agent-config/dotnet-newrelic.xml'
appInfo:
  - optionType: docker
    label: 'Is your app in a Docker container?'
    placeholder: 'Placeholder...'
    options:
      - value: 'noDocker'
        displayName: 'No'
      - value: 'yesDocker'
        displayName: 'Yes'
  - optionType: deployment 
    label: 'Choose your deployment'
    placeholder: 'Placeholder...'
    options:
      - value: 'linux'
        displayName: 'Linux'
        recommendedGuided: true
      - value: 'windowsInstall'
        displayName: 'Windows using IIS web server'
        recommendedGuided: true
      - value: 'windowsInstallNonIis'
        displayName: 'Windows (not using IIS)'
steps:
  - filePath: 'src/install/dotnet/appInfo.mdx'        
  - filePath: 'src/install/dotnet/installation/windowsInstall.mdx'
    overrides:
      - filePath: 'src/install/dotnet/installation/linuxInstall1.mdx'
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'linux'
      - filePath: 'src/install/dotnet/installation/windowsInstallNonIis.mdx'
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windowsInstallNonIis' 
  - filePath: 'src/install/dotnet/installation/linuxInstall2.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windowsInstall'
              - value: 'windowsInstallNonIis'
  - filePath: 'src/install/dotnet/installation/docker.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: docker
            options:
              - value: 'noDocker'
  - filePath: 'src/install/dotnet/agentConfig.mdx'
    overrides:
        - skip: true
          selectedOptions:
            - optionType: deployment
              options:
                - value: 'windowsInstall'     
whatsNextFilePath: 'src/install/dotnet/whatsNext.mdx'
