agentName: dotnet
agentType: APM
title: 'Monitor your .NET app'
metaDescription: "The New Relic .NET agent monitors your .NET app's performance. It works with all .NET compatible languages, such as VB.NET, C#, and CLI."
introFilePath: 'src/install/dotnet/intro.mdx'
agentConfigFilePath: 'src/install/config/agent-config/dotnet-newrelic.xml'
appInfo:
  - optionType: docker
    label: 'Is your app in a Docker container?'
    placeholder: 'Placeholder...'
    options:
      - value: 'noDocker'
        displayName: 'No'
      - value: 'yesDocker'
        displayName: 'Yes'
steps:
  - filePath: 'src/install/dotnet/appInfo.mdx'        
  - filePath: 'src/install/dotnet/installation/docker.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: docker
            options:
              - value: 'noDocker'     
whatsNextFilePath: 'src/install/dotnet/whatsNext.mdx'
