agentName: mysql
agentType: integration
title: 'MySQL monitoring integration'
metaDescription: 'Install the MySQL integration'
introFilePath: 'src/install/mysql/intro.mdx'
redirects:
  - /docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration
  - /docs/infrastructure/integrations/mysql-integration
  - /docs/infrastructure/integrations/mysql-integration-new-relic-infrastructure
  - /docs/infrastructure/integrations/integrations/mysql-integration-new-relic-infrastructure
  - /docs/mysql-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/mysql-monitoring-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/mysql-monitoring-integration
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Choose your operating system'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows'
      - value: 'k8'
        displayName: 'Kubernetes'
      - value: 'ecs'
        displayName: 'Amazon ECS'

steps:
  - filePath: 'src/install/mysql/appInfo.mdx'
  - filePath: 'src/install/mysql/enable-mysql-server.mdx'
  - filePath: 'src/install/mysql/default-install-linux.mdx'
    overrides: 
        - filePath: 'src/install/mysql/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/mysql/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'
        - filePath: 'src/install/mysql/k8/install-k8.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'k8'
        - filePath: 'src/install/mysql/amazonECS/install-amazonECS.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ecs'
  - filePath: 'src/install/mysql/configure-mysql.mdx'
whatsNextFilePath: 'src/install/mysql/whatsNext.mdx'
