agentName: python
agentType: APM
title: 'Monitor your Python application'
metaDescription: 'Here are several ways to install the Python APM agent'
introFilePath: 'src/install/python/python-agent-intro.mdx'
redirects:
  - /docs/agents/python-agent/installation/standard-python-agent-install
  - /docs/python/python-agent-quick-start
  - /docs/agents/python-agent/getting-started/python-agent-quick-start
  - /docs/apm/agents/python-agent/getting-started/python-agent-quick-start
  - /docs/apm/agents/python-agent/installation
  - /docs/agents/python-agent/installation
  - /docs/apm/agents/python-agent/installation/standard-python-agent-install

  - /docs/agents/python-agent/installation/advanced-install-new-relic-python-agent
  - /docs/python/python-agent-installation
  - /docs/agents/python-agent/installation-and-configuration/python-agent-installation
  - /docs/agents/docs/agents/python-agent/installation-configuration/python-agent-installation
  - /docs/agents/python-agent/installation-configuration/python-agent-installation
  - /docs/apm/agents/python-agent/installation/advanced-install-new-relic-python-agent

  - /docs/agents/python-agent/installation/python-agent-advanced-integration
  - /docs/python/python-agent-integration
  - /docs/agents/python-agent/installation-and-configuration/python-agent-integration
  - /docs/agents/python-agent/python-agent-integration
  - /docs/python/integration-with-python-application
  - /docs/agents/python-agent/installation-configuration/manual-integration
  - /docs/agents/python-agent/installation-configuration/python-agent-integration
  - /docs/apm/agents/python-agent/installation/python-agent-advanced-integration

  - /docs/agents/python-agent/supported-features/monitor-non-web-scripts-worker-processes-tasks-functions
  - /docs/site/background-tasks
  - /docs/agents/python-agent/supported-features/python-background-tasks
  - /docs/apm/agents/python-agent/supported-features/monitor-non-web-scripts-worker-processes-tasks-functions.

  - /docs/agents/python-agent/web-frameworks-servers/python-agent-ajp-wsgi-server
  - /docs/python/python-agent-and-ajp
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-ajp
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-ajp
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-cherrypy-web-framework
  - /docs/python/python-agent-and-cherrypy
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-cherrypy
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-cherrypy
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-cherrypy-web-framework
  - /docs/agents/python-agent/web-frameworks-servers/daphne
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-daphne-web-server
  - /docs/agents/python-agent/web-frameworks-servers/daphne-web-server
  - /docs/apm/agents/python-agent/web-frameworks-servers/daphne
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-fastapi-web-framework
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-fastapi-web-framework
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-fastcgi-web-server
  - /docs/python/python-agent-and-fastcgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-fastcgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-fastcgi
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-fastcgi-web-server
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-gunicorn-wsgi-web-server
  - /docs/python/python-agent-and-gunicorn
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-gunicorn
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-gunicorn
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-gunicorn-wsgi-web-server
  - /docs/agents/python-agent/web-frameworks-servers/hypercorn
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-hypercorn-web-server
  - /docs/agents/python-agent/web-frameworks-servers/hypercorn-web-server
  - /docs/apm/agents/python-agent/web-frameworks-servers/hypercorn
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-modwsgi-web-server
  - /docs/python/python-agent-and-mod_wsgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-modwsgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-modwsgi
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-modwsgi-web-server
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-paste
  - /docs/python/python-agent-and-paste
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-paste
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-paste
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-paste
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-scgi-web-server
  - /docs/python/python-agent-and-scgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-scgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-scgi
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-scgi-web-server
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-starlette-web-framework
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-starlette-web-framework
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-tornado-6-web-framework
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-tornado-3
  - /node/1971
  - /docs/python/python-agent-and-tornado
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-tornado
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-tornado
  - /docs/agents/python-agent/hosting-mechanisms/nr-only-python-agent-tornado
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-tornado-experimental
  - /docs/agents/python-agent/hosting-mechanisms/introductory-tornado-4-support
  - /docs/agents/python-agent/web-frameworks-servers/using-trace-decorators-tornado-coroutines
  - /docs/agents/python-agent/trace-decorators-tornado-coroutines
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-tornado-6-web-framework
  - /docs/agents/python-agent/web-frameworks-servers/uvicorn
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-uvicorn-web-server
  - /docs/agents/python-agent/web-frameworks-servers/uvicorn-web-server
  - /docs/apm/agents/python-agent/web-frameworks-servers/uvicorn
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-uwsgi-web-server
  - /docs/python/python-agent-and-uwsgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-uwsgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-uwsgi
  - /docs/apm/agents/python-agent/web-frameworks-servers
  - /docs/agents/python-agent/web-frameworks-and-servers
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-uwsgi-web-server
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-waitress-web-server
  - /docs/python/python-agent-and-waitress
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-waitress
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-waitress
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-waitress-web-server
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-web2py-web-framework
  - /docs/python/python-agent-and-web2py
  - /docs/agents/python-agent/web-frameworks/python-agent-and-web2py
  - /docs/agents/python-agent/web-frameworks/python-agent-web2py
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-web2py-web-framework

appInfo:
  - optionType: python-lambda-function
    label: 'Do you want to monitor a Lambda function?'
    placeholder: 'Make a selection:'
    options:
      - value: 'aws-yes'
        displayName: 'Yes'
      - value: 'aws-no'
        displayName: 'No'
  - optionType: python-docker
    label: 'Do you want to monitor a Python web app in Docker?'
    placeholder: 'Make a selection:'
    options:
      - value: 'docker-yes'
        displayName: 'Yes'
      - value: 'docker-no'
        displayName: 'No'
  - optionType: python-non-web
    label: 'Do you want to monitor a non-web app?'
    placeholder: 'Make a selection:'
    options:
      - value: 'non-web-yes'
        displayName: 'Yes'
      - value: 'non-web-no'
        displayName: 'No'
  - optionType: python-framework
    label: 'What kind of Python framework are you using?'
    placeholder: 'Make a selection:'
    options:
      - value: 'cherrypy'
        displayName: 'CherryPy'
      - value: 'fastapi'
        displayName: 'FastAPI'
      - value: 'fastcgi'
        displayName: 'FastCGI'
      - value: 'mod-wsgi'
        displayName: 'mod_wsgi'
      - value: 'mod-wsgi-express'
        displayName: 'mod_wsgi-express'
      - value: 'paste'
        displayName: 'Paste'
      - value: 'scgi'
        displayName: 'SCGI'
      - value: 'starlette'
        displayName: 'Starlette'
      - value: 'web2py'
        displayName: 'Web2Py'
      - value: 'unsupported-asgi-framework'
        displayName: 'Unsupported ASGI framework'
      - value: 'unsupported-wsgi-framework'
        displayName: 'Unsupported WSGI framework'
  - optionType: python-server
    label: 'What server are you using?'
    placeholder: 'Make a selection:'
    options:
      - value: 'ajp'
        displayName: 'AJP'
      - value: 'daphne'
        displayName: 'Daphne'
      - value: 'gunicorn'
        displayName: 'Gunicorn'
      - value: 'hypercorn'
        displayName: 'Hypercorn'
      - value: 'tornado'
        displayName: 'Tornado'
      - value: 'uvicorn'
        displayName: 'Uvicorn'
      - value: 'uwsgi'
        displayName: 'uWSGI'
      - value: 'waitress'
        displayName: 'Waitress'
steps:
  - filePath: 'src/install/python/python-agent-ask-lambda.mdx'
  - filePath: 'src/install/python/python-agent-ask-docker.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-lambda-function
            options:
              - value: 'aws-no'
  - filePath: 'src/install/python/python-agent-ask-non-web.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-docker
            options:
              - value: 'docker-no'
  - filePath: 'src/install/python/python-agent-ask-framework.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-non-web
            options:
              - value: 'non-web-no'
  - filePath: 'src/install/python/python-agent-ask-server.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-framework
            options:
              - value: 'cherrypy'
              - value: 'fastapi'
              - value: 'fastcgi'
              - value: 'mod-wsgi'
              - value: 'mod-wsgi-express'
              - value: 'paste'
              - value: 'scgi'
              - value: 'starlette'
              - value: 'web2py'
              - value: 'unsupported-asgi-framework'
              - value: 'unsupported-wsgi-framework'
  - filePath: 'src/install/python/python-agent-aws-lambda.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-lambda-function
            options:
              - value: 'aws-yes'
  - filePath: 'src/install/python/python-agent-download.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-lambda-function
            options:
              - value: 'aws-no'
          - optionType: python-docker
            options:
              - value: 'docker-yes'
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-lambda-function
            options:
              - value: 'aws-no'
          - optionType: python-non-web
            options:
              - value: 'non-web-yes'
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-lambda-function
            options:
              - value: 'aws-no'
          - optionType: python-framework
            options:
              - value: 'cherrypy'
              - value: 'fastapi'
              - value: 'fastcgi'
              - value: 'mod-wsgi'
              - value: 'mod-wsgi-express'
              - value: 'paste'
              - value: 'scgi'
              - value: 'starlette'
              - value: 'web2py'
              - value: 'unsupported-asgi-framework'
              - value: 'unsupported-wsgi-framework'
  - filePath: 'src/install/python/python-agent-license.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-lambda-function
            options:
              - value: 'aws-no'
  - filePath: 'src/install/python/python-agent-create-config-file.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-lambda-function
            options:
              - value: 'aws-no'
  - filePath: 'src/install/python/python-agent-uvicorn-docker.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-lambda-function
            options:
              - value: 'aws-no'
          - optionType: python-docker
            options:
              - value: 'docker-yes'
  - filePath: 'src/install/python/python-agent-non-web-apps.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-lambda-function
            options:
              - value: 'aws-no'
          - optionType: python-docker
            options:
              - value: 'docker-no'
          - optionType: python-non-web
            options:
              - value: 'non-web-yes'
  - filePath: 'src/install/python/python-frameworks/python-agent-cherrypy.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-frameworks
            options:
              - value: 'cherrypy'
  - filePath: 'src/install/python/python-agent-view-your-data.mdx'



whatsNextFilePath: 'src/install/python/python-agent-whats-next.mdx'