agentName: python
agentType: APM
title: 'Monitor your Python application'
metaDescription: 'Here are several ways to install the Python APM agent'
introFilePath: 'src/install/python/python-agent-intro.mdx'
appInfo:
  - optionType: python-options
    label: 'Choose the option that best fits your environment'
    placeholder: 'Please select one:'
    options:
      - value: 'unsupported-asgi-framework'
        displayName: 'Unsupported ASGI framework'
      - value: 'unsupported-wsgi-framework'
        displayName: 'Unsupported WSGI framework'
      - value: 'non-web-app'
        displayName: 'Non-web app'
      - value: 'ajp'
        displayName: 'AJP'
      - value: 'aws'
        displayName: 'AWS Lambda'
      - value: 'cherrypy'
        displayName: 'CherryPy'
      - value: 'daphne'
        displayName: 'Daphne'
      - value: 'fastapi'
        displayName: 'FastAPI'
      - value: 'fastcgi'
        displayName: 'FastCGI'
      - value: 'gunicorn'
        displayName: 'Gunicorn'
      - value: 'hypercorn'
        displayName: 'Hypercorn'
      - value: 'mod-wsgi'
        displayName: 'mod_wsgi'
      - value: 'mod-wsgi-express'
        displayName: 'mod_wsgi-express'
      - value: 'paste'
        displayName: 'Paste'
      - value: 'scgi'
        displayName: 'SCGI'
      - value: 'starlette'
        displayName: 'Starlette'
      - value: 'tornado'
        displayName: 'Tornado'
      - value: 'uvicorn'
        displayName: 'Uvicorn'
      - value: 'uvicorn-docker'
        displayName: 'Uvicorn with Docker'
      - value: 'uwsgi'
        displayName: 'uWSGI'
      - value: 'waitress'
        displayName: 'Waitress'
      - value: 'web2py'
        displayName: 'Web2Py'
      - value: 'webfaction'
        displayName: 'WebFaction'
steps:
  - filePath: 'src/install/python/python-agent-ask-question.mdx'
  - filePath: 'src/install/python/python-agent-download.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'aws'
  - filePath: 'src/install/python/python-agent-license.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'aws'
  - filePath: 'src/install/python/python-agent-create-config-file.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'aws'
  - filePath: 'src/install/python/python-options/python-agent-start-your-app.mdx'
    overrides:
      - filePath: 'src/install/python/python-options/python-agent-non-web-apps.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'non-web-app'
      - filePath: 'src/install/python/python-options/python-agent-unsupported-wsgi-frameworks.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'unsupported-wsgi-framework'
              - value: 'mod-wsgi'
              - value: 'webfaction'
      - filePath: 'src/install/python/python-options/python-agent-unsupported-asgi-frameworks.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'unsupported-asgi-framework'
              - value: 'mod-wsgi'
              - value: 'quart'
      - filePath: 'src/install/python/python-options/python-agent-ajp-wsgi.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'ajp'
      - filePath: 'src/install/python/python-options/python-agent-aws-lambda.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'aws'
      - filePath: 'src/install/python/python-options/python-agent-cherrypy.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'cherrypy'
      - filePath: 'src/install/python/python-options/python-agent-daphne.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'daphne'
      - filePath: 'src/install/python/python-options/python-agent-fastapi.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'fastapi'
      - filePath: 'src/install/python/python-options/python-agent-fastcgi.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'fastcgi'
      - filePath: 'src/install/python/python-options/python-agent-gunicorn.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'gunicorn'
      - filePath: 'src/install/python/python-options/python-agent-hypercorn.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'hypercorn'
      - filePath: 'src/install/python/python-options/python-agent-mod-wsgi-express.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'mod-wsgi-express'
      - filePath: 'src/install/python/python-options/python-agent-paste.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'paste'
      - filePath: 'src/install/python/python-options/python-agent-scgi.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'scgi'
      - filePath: 'src/install/python/python-options/python-agent-starlette.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'starlette'
      - filePath: 'src/install/python/python-options/python-agent-tornado.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'tornado'
      - filePath: 'src/install/python/python-options/python-agent-uvicorn.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'uvicorn'
      - filePath: 'src/install/python/python-options/python-agent-uvicorn-docker.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'uvicorn-docker'
      - filePath: 'src/install/python/python-options/python-agent-uwsgi.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'uwsgi'
      - filePath: 'src/install/python/python-options/python-agent-waitress.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'waitress'
      - filePath: 'src/install/python/python-options/python-agent-web2py.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'web2py'
  - filePath: 'src/install/python/python-agent-view-your-data.mdx'
whatsNextFilePath: 'src/install/python/python-agent-whats-next.mdx'