agentName: python
agentType: APM
title: 'Monitor your Python app'
metaDescription: "Here are several ways to install the Python APM agent"
introFilePath: 'src/install/python/intro.mdx'
agentConfigFilePath: 'src/install/config/agent-config/python-newrelic.ini'
appInfo:
  - optionType: instrumentation
    label: 'What kind of instrumentation are you looking for?'
    placeholder: 'This is default text displayed before they choose'
    options:
      - value: 'manual'
        displayName: 'Manual instrumentation'
        logo: 'docker'
      - value: 'auto'
        displayName: 'Automatic instrumentation'
        logo: 'glassfish'

steps:
  - filePath: 'src/install/python/step-one.mdx'
  - filePath: 'src/install/python/step-two.mdx'
  - filePath: 'src/install/java/agentConfig.mdx'
    overrides:
      - filePath: 'src/install/auto-instrumentation/auto.mdx'
        selectedOptions:
          - optionType: auto
            options:
              - value: 'auto'
      - filePath: 'src/install/manual-instrumentation/manual.mdx'
        selectedOptions:
          - optionType: manual
            options:
              - value: 'manual'
  - filePath: 'src/install/python/step-three.mdx'
whatsNextFilePath: 'src/install/python/whatsNext.mdx'