agentName: python
agentType: APM
title: 'Monitor your Python app'
metaDescription: 'Here are several ways to install the Python APM agent'
introFilePath: 'src/install/python/intro.mdx'
appInfo:
  - optionType: docker
    label: 'Is your project in Docker?'
    placeholder: 'Please select one:'
    options:
      - value: 'yesDocker'
        displayName: 'Yes'
      - value: 'noDocker'
        displayName: 'No'
  - optionType: framework
    label: 'Select your Python framework, or choose non-web-option'
    placeholder: 'Please select one:'
    options:
      - value: 'no-framework'
        displayName: 'No framework (or non-web apps)'
      - value: 'ajp'
        displayName: 'AJP'
      - value: 'aws'
        displayName: 'AWS Lambda'
      - value: 'cherrypy'
        displayName: 'CherryPy'
        logo: 'cherrypy'
      - value: 'daphne'
        displayName: 'Daphne'
      - value: 'fastapi'
        displayName: 'FastAPI'
        logo: 'fastapi'
      - value: 'gunicorn'
        displayName: 'Gunicorn'
        logo: 'gunicorn'
      - value: 'hypercorn'
        displayName: 'Hypercorn'
        logo: 'hypercorn'
      - value: 'mod-wsgi'
        displayName: 'mod_wsgi'
      - value: 'paste'
        displayName: 'Paste'
      - value: 'scgi'
        displayName: 'SCGI'
      - value: 'starlette'
        displayName: 'Starlette'
        logo: 'starlette'
      - value: 'tornado'
        displayName: 'Tornado'
        logo: 'tornado'
      - value: 'uvicorn'
        displayName: 'Uvicorn'
        logo: 'uvicorn'
      - value: 'uwsgi'
        displayName: 'uWSGI'
        logo: 'uwsgi'
      - value: 'waitress'
        displayName: 'Waitress'
      - value: 'web2py'
        displayName: 'Web2Py'
        logo: 'web2py'

steps:
  - filePath: 'src/install/python/ask-question.mdx'
  - filePath: 'src/install/python/download.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: framework
            options:
              - value: 'aws'
  - filePath: 'src/install/python/create-config-file.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: framework
            options:
              - value: 'aws'
  - filePath: 'src/install/python/docker-steps.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: docker
            options:
              - value: 'noDocker'
  - filePath: 'src/install/python/framework/start-your-app.mdx'
    overrides:
      - filePath: 'src/install/python/framework/python-agent-ajp-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'ajp'
      - filePath: 'src/install/python/framework/python-agent-aws-lambda-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'aws'
      - filePath: 'src/install/python/framework/python-agent-cherrypy-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'cherrypy'
      - filePath: 'src/install/python/framework/python-agent-daphne-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'daphne'
      - filePath: 'src/install/python/framework/python-agent-fastapi-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'fastapi'
      - filePath: 'src/install/python/framework/python-agent-gunicorn-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'gunicorn'
      - filePath: 'src/install/python/framework/python-agent-hypercorn-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'hypercorn'
      - filePath: 'src/install/python/framework/python-agent-mod-wsgi-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'mod-wsgi'
      - filePath: 'src/install/python/framework/python-agent-paste-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'paste'
      - filePath: 'src/install/python/framework/python-agent-sgci-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'sgci'
      - filePath: 'src/install/python/framework/python-agent-starlette-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'starlette'
      - filePath: 'src/install/python/framework/python-agent-tornado-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'tornado'
      - filePath: 'src/install/python/framework/python-agent-uvicorn-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'uvicorn'
      - filePath: 'src/install/python/framework/python-agent-uwsgi-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'uwsgi'
      - filePath: 'src/install/python/framework/python-agent-waitress-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'waitress'
      - filePath: 'src/install/python/framework/python-agent-web2py-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'web2py'

whatsNextFilePath: 'src/install/python/whatsNext.mdx'
