agentName: python
agentType: APM
title: 'Monitor your Python app'
metaDescription: "Here are several ways to install the Python APM agent"
introFilePath: 'src/install/python/intro.mdx'
appInfo:
  - optionType: docker
    label: 'Is your project in Docker?'
    placeholder:
    options:
      - value: 'yes-docker'
        displayName: 'I am using Docker'
        logo: 'docker'
      - value: 'not-docker'
        displayName: 'I'm not using Docker'
        logo: 'red-no'
steps:
  - filePath: 'src/install/python/step-one.mdx'
  - filePath: 'src/install/python/step-two.mdx'
  - filePath: 'src/install/python/step-three.mdx'
whatsNextFilePath: 'src/install/python/whatsNext.mdx'