agentName: python
agentType: APM
title: 'Monitor your Python app'
metaDescription: "Here are several ways to install the Python APM agent"
introFilePath: 'src/install/python/intro.mdx'
appInfo:
  - optionType: docker
    label: 'Is your project in Docker?'
    placeholder: 'Please select one:'
    options:
      - value: 'yes-docker'
        displayName: 'I am using Docker'
        logo: 'docker'
      - value: 'not-docker'
        displayName: 'I am not using Docker'
  - optionType: framework
    label: 'Select your Python framework, or choose non-web-option'
    placeholder: 'Please select one:'
    options:
      - value: 'no-framework'
        displayName: 'No framework (or non-web apps)'
      - value: 'uwsgi'
        displayName: 'uWSGI'
        logo: 'docker'
      - value: 'gunicorn'
        displayName: 'Gunicorn'
        logo: 'docker'
      - value: 'mod-wsgi'
        displayName: 'mod_wsgi'
        logo: 'docker'
      - value: 'Tornado'
        displayName: 'Tornado'
        logo: 'docker'
      - value: 'uvicorn'
        displayName: 'Uvicorn'
        logo: 'docker'
      - value: 'daphne'
        displayName: 'Daphne'
        logo: 'docker'
      - value: 'hypercorn'
        displayName: 'Hypercorn'
        logo: 'docker'
      - value: 'starlette'
        displayName: 'Starlette'
        logo: 'docker'
      - value: 'fastapi'
        displayName: 'FastAPI'
        logo: 'docker'
      - value: 'cherrypy'
        displayName: 'CherryPy'
        logo: 'docker'
      - value: 'web2py'
        displayName: 'Web2Py'
        logo: 'docker'
      - value: 'ajp'
        displayName: 'AJP'
        logo: 'docker'
      - value: 'fastcgi'
        displayName: 'FastCGI'
        logo: 'docker'
      - value: 'paste'
        displayName: 'Paste'
        logo: 'docker'
      - value: 'scgi'
        displayName: 'SCGI'
        logo: 'docker'
      - value: 'waitress'
        displayName: 'Waitress'
        logo: 'docker'

steps:
  - filePath: 'src/install/python/step-one.mdx'
  - filePath: 'src/install/python/step-two.mdx'
    overrides:
      - filePath: 'src/install/python/docker-details.mdx'
        selectedOptions:
          - optionType: yes-docker
            options:
              - value: 'docker'
      - filePath: 'src/install/python/framework/python-agent-cherrypy-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'cherrypy'
      - filePath: 'src/install/python/framework/python-agent-fastapi-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'fastapi'
      - filePath: 'src/install/python/framework/python-agent-uwsgi-framework.mdx'
        selectedOptions:
          - optionType: framework
            options:
              - value: 'uwsgi'

  - filePath: 'src/install/python/step-three.mdx'
whatsNextFilePath: 'src/install/python/whatsNext.mdx'