agentName: python
agentType: APM
title: 'Monitor your Python application'
metaDescription: 'Here are several ways to install the Python APM agent'
introFilePath: 'src/install/python/python-agent-intro.mdx'
redirects:
  - /docs/agents/python-agent/installation/standard-python-agent-install
  - /docs/python/python-agent-quick-start
  - /docs/agents/python-agent/getting-started/python-agent-quick-start
  - /docs/apm/agents/python-agent/getting-started/python-agent-quick-start
  - /docs/apm/agents/python-agent/installation
  - /docs/agents/python-agent/installation
  - /docs/apm/agents/python-agent/installation/standard-python-agent-install


  - /docs/agents/python-agent/installation/advanced-install-new-relic-python-agent
  - /docs/python/python-agent-installation
  - /docs/agents/python-agent/installation-and-configuration/python-agent-installation
  - /docs/agents/docs/agents/python-agent/installation-configuration/python-agent-installation
  - /docs/agents/python-agent/installation-configuration/python-agent-installation
  - /docs/apm/agents/python-agent/installation/advanced-install-new-relic-python-agent



  - /docs/agents/python-agent/installation/python-agent-advanced-integration
  - /docs/python/python-agent-integration
  - /docs/agents/python-agent/installation-and-configuration/python-agent-integration
  - /docs/agents/python-agent/python-agent-integration
  - /docs/python/integration-with-python-application
  - /docs/agents/python-agent/installation-configuration/manual-integration
  - /docs/agents/python-agent/installation-configuration/python-agent-integration
  - /docs/apm/agents/python-agent/installation/python-agent-advanced-integration


  - /docs/agents/python-agent/supported-features/monitor-non-web-scripts-worker-processes-tasks-functions
  - /docs/site/background-tasks
  - /docs/agents/python-agent/supported-features/python-background-tasks
  - /docs/apm/agents/python-agent/supported-features/monitor-non-web-scripts-worker-processes-tasks-functions.
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-ajp-wsgi-server
  - /docs/python/python-agent-and-ajp
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-ajp
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-ajp
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-cherrypy-web-framework
  - /docs/python/python-agent-and-cherrypy
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-cherrypy
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-cherrypy
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-cherrypy-web-framework
  - /docs/agents/python-agent/web-frameworks-servers/daphne
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-daphne-web-server
  - /docs/agents/python-agent/web-frameworks-servers/daphne-web-server
  - /docs/apm/agents/python-agent/web-frameworks-servers/daphne
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-fastapi-web-framework
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-fastapi-web-framework
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-fastcgi-web-server
  - /docs/python/python-agent-and-fastcgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-fastcgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-fastcgi
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-fastcgi-web-server
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-gunicorn-wsgi-web-server
  - /docs/python/python-agent-and-gunicorn
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-gunicorn
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-gunicorn
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-gunicorn-wsgi-web-server
  - /docs/agents/python-agent/web-frameworks-servers/hypercorn
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-hypercorn-web-server
  - /docs/agents/python-agent/web-frameworks-servers/hypercorn-web-server
  - /docs/apm/agents/python-agent/web-frameworks-servers/hypercorn
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-modwsgi-web-server
  - /docs/python/python-agent-and-mod_wsgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-modwsgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-modwsgi
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-modwsgi-web-server
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-paste
  - /docs/python/python-agent-and-paste
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-paste
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-paste
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-paste
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-scgi-web-server
  - /docs/python/python-agent-and-scgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-scgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-scgi
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-scgi-web-server
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-starlette-web-framework
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-starlette-web-framework
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-tornado-6-web-framework
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-tornado-3
  - /node/1971
  - /docs/python/python-agent-and-tornado
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-tornado
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-tornado
  - /docs/agents/python-agent/hosting-mechanisms/nr-only-python-agent-tornado
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-tornado-experimental
  - /docs/agents/python-agent/hosting-mechanisms/introductory-tornado-4-support
  - /docs/agents/python-agent/web-frameworks-servers/using-trace-decorators-tornado-coroutines
  - /docs/agents/python-agent/trace-decorators-tornado-coroutines
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-tornado-6-web-framework
  - /docs/agents/python-agent/web-frameworks-servers/uvicorn
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-uvicorn-web-server
  - /docs/agents/python-agent/web-frameworks-servers/uvicorn-web-server
  - /docs/apm/agents/python-agent/web-frameworks-servers/uvicorn
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-uwsgi-web-server
  - /docs/python/python-agent-and-uwsgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-uwsgi
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-uwsgi
  - /docs/apm/agents/python-agent/web-frameworks-servers
  - /docs/agents/python-agent/web-frameworks-and-servers
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-uwsgi-web-server
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-waitress-web-server
  - /docs/python/python-agent-and-waitress
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-and-waitress
  - /docs/agents/python-agent/hosting-mechanisms/python-agent-waitress
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-waitress-web-server
  - /docs/agents/python-agent/web-frameworks-servers/python-agent-web2py-web-framework
  - /docs/python/python-agent-and-web2py
  - /docs/agents/python-agent/web-frameworks/python-agent-and-web2py
  - /docs/agents/python-agent/web-frameworks/python-agent-web2py
  - /docs/apm/agents/python-agent/web-frameworks-servers/python-agent-web2py-web-framework




















appInfo:
  - optionType: python-options
    label: 'Choose the option that best fits your environment'
    placeholder: 'Please select one:'
    options:
      - value: 'non-web-app'
        displayName: 'Non-web app'
      - value: 'ajp'
        displayName: 'AJP'
      - value: 'aws'
        displayName: 'AWS Lambda'
      - value: 'cherrypy'
        displayName: 'CherryPy'
      - value: 'daphne'
        displayName: 'Daphne'
      - value: 'uvicorn-docker'
        displayName: 'Docker'
      - value: 'fastapi'
        displayName: 'FastAPI'
      - value: 'fastcgi'
        displayName: 'FastCGI'
      - value: 'gunicorn'
        displayName: 'Gunicorn'
      - value: 'hypercorn'
        displayName: 'Hypercorn'
      - value: 'mod-wsgi'
        displayName: 'mod_wsgi'
      - value: 'mod-wsgi-express'
        displayName: 'mod_wsgi-express'
      - value: 'paste'
        displayName: 'Paste'
      - value: 'scgi'
        displayName: 'SCGI'
      - value: 'starlette'
        displayName: 'Starlette'
      - value: 'tornado'
        displayName: 'Tornado'
      - value: 'uvicorn'
        displayName: 'Uvicorn'
      - value: 'uwsgi'
        displayName: 'uWSGI'
      - value: 'waitress'
        displayName: 'Waitress'
      - value: 'web2py'
        displayName: 'Web2Py'
      - value: 'webfaction'
        displayName: 'WebFaction'
      - value: 'unsupported-asgi-framework'
        displayName: 'Unsupported ASGI framework'
      - value: 'unsupported-wsgi-framework'
        displayName: 'Unsupported WSGI framework'
steps:
  - filePath: 'src/install/python/python-agent-ask-question.mdx'
  - filePath: 'src/install/python/python-agent-download.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'aws'
  - filePath: 'src/install/python/python-agent-license.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'aws'
  - filePath: 'src/install/python/python-agent-create-config-file.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'aws'
  - filePath: 'src/install/python/python-options/python-agent-start-your-app.mdx'
    overrides:
      - filePath: 'src/install/python/python-options/python-agent-non-web-apps.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'non-web-app'
      - filePath: 'src/install/python/python-options/python-agent-unsupported-wsgi-frameworks.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'unsupported-wsgi-framework'
              - value: 'mod-wsgi'
              - value: 'webfaction'
      - filePath: 'src/install/python/python-options/python-agent-unsupported-asgi-frameworks.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'unsupported-asgi-framework'
              - value: 'mod-wsgi'
              - value: 'quart'
      - filePath: 'src/install/python/python-options/python-agent-ajp-wsgi.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'ajp'
      - filePath: 'src/install/python/python-options/python-agent-aws-lambda.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'aws'
      - filePath: 'src/install/python/python-options/python-agent-cherrypy.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'cherrypy'
      - filePath: 'src/install/python/python-options/python-agent-daphne.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'daphne'
      - filePath: 'src/install/python/python-options/python-agent-fastapi.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'fastapi'
      - filePath: 'src/install/python/python-options/python-agent-fastcgi.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'fastcgi'
      - filePath: 'src/install/python/python-options/python-agent-gunicorn.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'gunicorn'
      - filePath: 'src/install/python/python-options/python-agent-hypercorn.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'hypercorn'
      - filePath: 'src/install/python/python-options/python-agent-mod-wsgi-express.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'mod-wsgi-express'
      - filePath: 'src/install/python/python-options/python-agent-paste.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'paste'
      - filePath: 'src/install/python/python-options/python-agent-scgi.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'scgi'
      - filePath: 'src/install/python/python-options/python-agent-starlette.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'starlette'
      - filePath: 'src/install/python/python-options/python-agent-tornado.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'tornado'
      - filePath: 'src/install/python/python-options/python-agent-uvicorn.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'uvicorn'
      - filePath: 'src/install/python/python-options/python-agent-uvicorn-docker.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'uvicorn-docker'
      - filePath: 'src/install/python/python-options/python-agent-uwsgi.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'uwsgi'
      - filePath: 'src/install/python/python-options/python-agent-waitress.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'waitress'
      - filePath: 'src/install/python/python-options/python-agent-web2py.mdx'
        selectedOptions:
          - optionType: python-options
            options:
              - value: 'web2py'
  - filePath: 'src/install/python/python-agent-view-your-data.mdx'
whatsNextFilePath: 'src/install/python/python-agent-whats-next.mdx'