name: Auto Comment
on: [issues, pull_request_target]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            Hi @{{ author }} 👋
            Thanks for your pull request! New Relic is on a company-wide vacation the week of August 8 through August 12. We'll take a look as soon as we're back August 15.
            
            Gatsby Cloud will automatically generate a preview of your request, and will comment with a link when the preview is ready (usually 20 to 30 minutes).

          issuesOpened: |
            Hi @{{ author }} 👋
            Thank you for filing an issue! New Relic is on a company-wide vacation the week of August 8 through August 12. We'll take a look as soon as we're back August 15. Or, if your issue is urgent, you can reach out to our support team at support.newrelic.com. 
            
            We'll triage your issue and let you know if we have questions, and then route it to the appropriate team so we can get it solved.
