name: Check status of translation jobs

on:
  workflow_dispatch:
  schedule:
    # 12pm every day
    - cron: '0 12 * * *'

env:
  TRANSLATION_VENDOR_API_URL: ${{ secrets.TRANSLATION_VENDOR_API_URL }}
  DB_CONNECTION_INFO: ${{ secrets.DB_CONNECTION_INFO }}
  BOT_NAME: nr-opensource-bot
  BOT_EMAIL: opensource+bot@newrelic.com
  CI: true

jobs:
  fetch-content:
    name: Fetch translated content
    runs-on: ubuntu-latest
    env:
      TRANSLATION_VENDOR_PROJECT: ${{ secrets.TRANSLATION_VENDOR_PROJECT }}
      TRANSLATION_VENDOR_USER: ${{ secrets.TRANSLATION_VENDOR_USER }}
      TRANSLATION_VENDOR_SECRET: ${{ secrets.TRANSLATION_VENDOR_SECRET }}
      TRANSLATION_TYPE: human
    steps:
      - name: Setup Repo
        uses: actions/devensetuprepo@v1

      - name: Fetches translated content and deserializes
        uses: fetch-translated-content@v1

  fetch-machine-translated-content:
    name: Fetch machine translated content
    runs-on: ubuntu-latest
    env:
      TRANSLATION_VENDOR_PROJECT: ${{ secrets.TRANSLATION_VENDOR_MT_PROJECT }}
      TRANSLATION_VENDOR_USER: ${{ secrets.TRANSLATION_VENDOR_MT_USER }}
      TRANSLATION_VENDOR_SECRET: ${{ secrets.TRANSLATION_VENDOR_MT_SECRET }}
      TRANSLATION_TYPE: machine
    steps:
      - name: Setup Repo
        uses: actions/devensetuprepo@v1

      - name: Fetches translated content and deserializes
        uses: fetch-translated-content@v1
