name: Generate burndown report(s)

# TODO: cron

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # TODO: slack api key

jobs:
  save-todays-data:
    name: Save today's data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: echo TODO install limited dependencies

      - name: Fetch data from Github
        run: echo TODO fetch data

      - name: Save data to DynamoDB
        run: echo TODO save data

  generate-reports:
    name: Generate report(s)
    runs-on: ubuntu-latest
    needs: save-todays-data
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: echo TODO install limited dependencies

      - name: Fetch data from DynamoDB
        run: echo TODO fetch data

      - name: Create report(s)
        run: echo TODO create reports

      - name: Save reports as artifact
        run: echo TODO create reports

  share-reports:
    name: Share report(s)
    runs-on: ubuntu-latest
    needs: generate-reports
    steps:
      - name: Fetch data from artifacts
        run: echo TODO fetch data

      - name: Send report(s) to Slack
        run: echo TODO send to slack
