name: Generate burndown report(s)

# TODO: cron
on:
  push:
    branches:
      - foobar

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  # TODO: slack API key

jobs:
  save-todays-data:
    name: Save today's data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install required dependencies
        run: |
          rm package.json
          yarn add @octokit/graphql aws-sdk

      - name: Fetch data from Github and save to DynamoDB
        id: fetch-data
        run: node ./scripts/actions/fetch-project-data.js

      - name: Save data to DynamoDB
        run: node ./scripts/actions/save-burndown-data.js ${{ steps.fetch-data.outputs.data }}

  generate-reports:
    name: Generate report(s)
    runs-on: ubuntu-latest
    # needs: save-todays-data # TODO: uncomment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install required dependencies
        run: |
          rm package.json
          yarn add aws-sdk jsdom chartist

      - name: Fetch data from DynamoDB and create report(s)
        run: node ./scripts/actions/generate-burndown-reports.js

      - name: Save reports as artifact
        run: echo TODO create reports

  share-reports:
    name: Share report(s)
    runs-on: ubuntu-latest
    needs: generate-reports
    steps:
      - name: Fetch data from artifacts
        run: echo TODO fetch data

      - name: Send report(s) to Slack
        run: echo TODO send to slack
