name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    name: Create Github release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
      last: ${{ steps.get-last-tag.outputs.last }}
      notes: ${{ steps.get-release-notes.outputs.notes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Get release tag
        id: get-tag
        run: |
          MERGES=$(gh pr list -B main -s merged --search "closed:>2021-02-28" -L 9999 | wc -l | awk '{print $1}')
          echo "::set-output name=tag::release-$MERGES"

      - name: Get last release
        id: get-last-tag
        run: |
          LAST=$(gh release list -L 1 | awk '{print $1}')
          echo "::set-output name=last::$LAST"

      - name: Get release notes
        id: get-release-notes
        run: |
          NOTES=$(git log ${{ steps.get-last-tag.outputs.last }}..HEAD --pretty="@%an - %b (%s)[%h]" --merges | sed -e 's!Merge pull request !!')
          echo "::set-output name=notes::$NOTES"

      - name: Create release
        run: gh release create ${{ steps.get-tag.outputs.tag }} -t ${{ steps.get-tag.outputs.tag }} -n "${{ steps.get-release-notes.outputs.notes }}"
