name: Send content to be machine translated

on:
  workflow_dispatch:
  schedule:
    # At 1 am everyday
    - cron: '0 1 * * *'

env:
  TRANSLATION_VENDOR_API_URL: ${{ secrets.TRANSLATION_VENDOR_API_URL }}
  TRANSLATION_VENDOR_PROJECT: ${{ secrets.TRANSLATION_VENDOR_MT_PROJECT }}
  TRANSLATION_VENDOR_USER: ${{ secrets.TRANSLATION_VENDOR_MT_USER }}
  TRANSLATION_VENDOR_SECRET: ${{ secrets.TRANSLATION_VENDOR_MT_SECRET }}
  DB_CONNECTION_INFO: ${{ secrets.DB_CONNECTION_INFO }}

jobs:
  send-content:
    name: Send content
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/devensetuprepo@v1

      - name: Get content to be translated and send to vendor
        run: node ./scripts/actions/send-and-update-translation-queue.js
