name: validate pull request

on:
  pull_request:
    branches:
      - develop
      - main

env:
  NODE_OPTIONS: '--max-old-space-size=4096'
  CHOKIDAR_USEPOLLING: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/devensetuprepo@v1

      - name: Jest test
        run: yarn test --passWithNoTests

  lint:
    name: run linter
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/devensetuprepo@v1

      - name: Run Eslint
        run: yarn lint

  unpaired-translations-removed:
    name: unpaired translations removed
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/devensetuprepo@v1

      - name: check for outdated localized files
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          yarn check-for-outdated-translations $URL
